/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2019-07-20

The MIT License (MIT)
Copyright (c) 2019 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include "stm32f0xx.h"
#include <stdbool.h>

/* Private macro */
/* Private variables */

/* Private function prototypes */
void delay(uint32_t);
void init_button();
bool flag = false;
/* Private functions */

/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/
//
volatile uint32_t ticks_delay = 0;

int main(void)
{

  uint32_t i = 0;


  /* TODO - Add your application code here */

  RCC->AHBENR |= RCC_AHBENR_GPIOCEN;
  SET_BIT(GPIOC->MODER,GPIO_MODER_MODER7_0);
  CLEAR_BIT(GPIOC-> OTYPER,GPIO_OTYPER_OT_7);
  CLEAR_BIT(GPIOC->OSPEEDR,GPIO_OSPEEDR_OSPEEDR7_0);


  SET_BIT(GPIOC->MODER,GPIO_MODER_MODER9_0);
  CLEAR_BIT(GPIOC->OTYPER,GPIO_OTYPER_OT_9);
  CLEAR_BIT(GPIOC->OSPEEDR,GPIO_OSPEEDR_OSPEEDR9_0);


  /*включить HSE*/
  SET_BIT(RCC->CR, RCC_CR_HSEON);
  /*ждём пока не включится HSE*/
  while(!(RCC->CR & RCC_CR_HSERDY));
  /*выбираем HSE как SYSCLK */
  SET_BIT(RCC->CFGR, RCC_CFGR_SW_HSE);
  while(!(RCC->CFGR & RCC_CFGR_SWS_HSE));
//flash
  SET_BIT(FLASH->ACR,FLASH_ACR_LATENCY);
  SET_BIT(FLASH->ACR,FLASH_ACR_PRFTBE);
  //принудительно отключаем PLL
  CLEAR_BIT(RCC->CR, RCC_CR_PLLON);
  //ставим источник PLL как сигнал с HSI, делённый предделителями PLL
  SET_BIT(RCC->CFGR, RCC_CFGR_PLLSRC_HSE_PREDIV);

  //предделитель
  SET_BIT(RCC->CFGR2,RCC_CFGR2_PREDIV_DIV1);
//множитель 2 у плл
  SET_BIT(RCC->CFGR, RCC_CFGR_PLLMUL3);

  //вкл плл
   SET_BIT(RCC->CR, RCC_CR_PLLON);

   /*ожидание вкл плл*/
   while(!(RCC->CR & RCC_CR_PLLRDY));

// pll источник sysclk
  CLEAR_BIT(RCC->CFGR,RCC_CFGR_SW);
  SET_BIT(RCC->CFGR, RCC_CFGR_SW_PLL);
//выбор
  while(!(RCC->CFGR & RCC_CFGR_SWS_PLL));

//
//SysTick->LOAD =  24000000UL/1000 - 1;
//SysTick->VAL  = 24000000UL/1000 - 1; // Устанавливаем текущее значение
//// Настраиваем таймеp

  SysTick_Config(SystemCoreClock*3/1000);

SET_BIT(RCC->CR,RCC_CR_CSSON);
  /*
   * Конфигурирование PA8 как MCO
   */
  SET_BIT(RCC->AHBENR,RCC_AHBENR_GPIOAEN);
  SET_BIT(GPIOA->MODER,GPIO_MODER_MODER8_1);
  CLEAR_BIT(GPIOA->OTYPER,GPIO_OTYPER_OT_8);

  CLEAR_BIT(GPIOA->OSPEEDR,GPIO_OSPEEDR_OSPEEDR8);
  SET_BIT(GPIOA->OSPEEDR,GPIO_OSPEEDR_OSPEEDR8_0);
  SET_BIT(GPIOA->OSPEEDR,GPIO_OSPEEDR_OSPEEDR8_1);

  CLEAR_BIT(RCC->CFGR, RCC_CFGR_MCO);


  /*
   * выводим на MCO SYSCLK
   */
  SET_BIT(RCC->CFGR,RCC_CFGR_MCO_SYSCLK);

//кнопка
  init_button();
  CLEAR_BIT(GPIOC->ODR,GPIO_ODR_9);


  /* Infinite loop */
  while (1)
  {
	  SET_BIT(GPIOC->ODR,GPIO_ODR_7);
//	  for(int i = 0; i<500000; i++){}
	  delay(50);
	  CLEAR_BIT(GPIOC->ODR,GPIO_ODR_7);
//	  for(int i = 0; i<500000; i++){}
	  delay(50);

//	  if ((GPIOA->IDR & GPIO_IDR_0)== GPIO_IDR_0)
//		  SET_BIT(GPIOC->ODR,GPIO_ODR_9);
//  else   CLEAR_BIT(GPIOC->ODR,GPIO_ODR_9);

	  if(flag)
		  SET_BIT(GPIOC->ODR,GPIO_ODR_9);
	  else
		  CLEAR_BIT(GPIOC->ODR,GPIO_ODR_9);
  }
}


void  EXTI0_1_IRQHandler()
{
	if ((GPIOA->IDR & GPIO_IDR_0)== GPIO_IDR_0)
		flag = 1;
	else
		flag = 0;

	EXTI->PR |= EXTI_PR_PR0;
}

void init_button()
{
 RCC->AHBENR |= RCC_AHBENR_GPIOAEN;
NVIC_EnableIRQ(EXTI0_1_IRQn);
SET_BIT(EXTI->IMR,EXTI_IMR_MR0);
SET_BIT(EXTI->RTSR,EXTI_RTSR_RT0);//верхний фронт
SET_BIT(EXTI->FTSR,EXTI_FTSR_TR0);//нижний фронт
}

void delay(const uint32_t milliseconds)
{
		uint32_t  start = ticks_delay;
	    while((ticks_delay - start) < milliseconds);
}

void SysTick_Handler(void)
{
 ticks_delay++;
}

void NMI_Handler(void)
{
    if (RCC->CIR & RCC_CIR_CSSF)
    {
    	SET_BIT(RCC->CIR,RCC_CIR_CSSC);
    	SET_BIT(GPIOC->ODR,GPIO_ODR_9);
	 SysTick_Config(SystemCoreClock/1000);
    }


}
